name: management_taks_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.4.2
  firebase_core: 1.19.2
  get: 4.6.5
  google_sign_in: ^5.4.0
  firebase_auth_web: ^4.0.0
 
  google_sign_in_web: ^0.10.2
  cloud_firestore: 3.4.3
  date_time_picker: 2.1.0
 
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/image/
  uses-material-design: true

