// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWZmAfzA59LSXhrg2WJLgVMtNs9n3zPpI',
    appId: '1:953534661037:web:6daed01d26e04d14362124',
    messagingSenderId: '953534661037',
    projectId: 'majid-uas',
    authDomain: 'majid-uas.firebaseapp.com',
    storageBucket: 'majid-uas.appspot.com',
    measurementId: 'G-CBHV8CHW67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV70MlXRN1di8bp72oDkrQ-1DhLPyVivI',
    appId: '1:953534661037:android:c4977af94ff15d6c362124',
    messagingSenderId: '953534661037',
    projectId: 'majid-uas',
    storageBucket: 'majid-uas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkIFVJ81utpY5noCyrBdsV_rm6aSkWmqA',
    appId: '1:953534661037:ios:127aa8639c20540a362124',
    messagingSenderId: '953534661037',
    projectId: 'majid-uas',
    storageBucket: 'majid-uas.appspot.com',
    iosClientId: '953534661037-m16jgpph60rffjo0hg4jep1oihvfd9j8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileProgrammingRouf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkIFVJ81utpY5noCyrBdsV_rm6aSkWmqA',
    appId: '1:953534661037:ios:127aa8639c20540a362124',
    messagingSenderId: '953534661037',
    projectId: 'majid-uas',
    storageBucket: 'majid-uas.appspot.com',
    iosClientId: '953534661037-m16jgpph60rffjo0hg4jep1oihvfd9j8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileProgrammingRouf',
  );
}
